### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ARtronClassicStudio** [keijiro/AIShader#10]
Hi, I decided to try and ran into this problem:

![image](https://user-images.githubusercontent.com/68843488/234618385-7dd87b62-d57d-4a72-9dc6-641ecb4bba0c.png)

Text Error:
Assets\OpenAI\Editor\OpenAIUtil.cs(26,28): error CS1503: Argument 2: cannot convert from 'string' to 'System.Collections.Generic.List<UnityEngine.Networking.IMultipartFormSection>'

![image](https://user-images.githubusercontent.com/68843488/234618595-1383a89b-fb19-4e51-b4c8-b5db9b3a5eea.png)

Use Unity 2021.3.23f1

**Comment by keijiro** [comment]
Please check the Unity version. It requires 2022.2 or later.

**Comment by keijiro** [comment]
I close this issue as answered. Please reopen it if it still reproduces.
