### ISSUE TITLE
Reliability

### ISSUE THREAD

**Issue by moonlockwood** [keijiro/AIShader#11]
I have been experimenting with using gpt4 in programming tasks and I've found that if you ask it to pretend it's a compiler and imagine what would happen when it runs it will return good code (if it is in the right mood!)

Using models and instances together is very powerful, you can have gpt4 check its own work, but the tokens add up quickly.

**Comment by keijiro** [comment]
Thanks for the suggestion. Although I don't have any plans for updating this project further, that sounds an interesting idea. I'll consider it in future projects.
