### ISSUE TITLE
Null Reference Exception on a fresh project

### ISSUE THREAD

**Issue by davididev** [keijiro/AIShader#12]
First debug message: Rebuilding Library because the asset database could not be found!

Exception when I click "Generate" on the example:
NullReferenceException: Object reference not set to an instance of an object
AIShader.OpenAIUtil.InvokeChat (System.String prompt) (at Assets/Editor/OpenAIUtil.cs:48)
AIShader.AIShaderImporterEditor.Regenerate () (at Assets/Editor/AIShaderImporterEditor.cs:28)
AIShader.AIShaderImporterEditor.OnInspectorGUI () (at Assets/Editor/AIShaderImporterEditor.cs:51)
UnityEditor.UIElements.InspectorElement+<>c__DisplayClass71_0.<CreateIMGUIInspectorFromEditor>b__0 () (at <d18341e808be4529a1a4512a7e51ab3d>:0)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr, Boolean&)

**Comment by keijiro** [comment]
Please check #1
