### ISSUE TITLE
You exceeded your current quota, please check your plan and billing details

### ISSUE THREAD

**Issue by zORg-alex** [keijiro/AIShader#14]
I get 'You exceeded your current quota, please check your plan and billing details' error in OpenAIUtil.cs:46
I've got OpenAI+ plan. What am I missing? I've just subscribed. All quotas are at 0.

**Comment by keijiro** [comment]
> I've got OpenAI+ plan.

Did you mean the ChatGPT Plus plan?

ChatGPT Plus is not relevant to the ChatGPT API. You have to pay for the API usage.

**Comment by zORg-alex** [comment]
Ah, I need to add card info in billing section. Would be nice to add that part in Readme
