### ISSUE TITLE
NullReferenceException: AIShader.OpenAIUtil.InvokeChat

### ISSUE THREAD

**Issue by diegoguisasolap** [keijiro/AIShader#3]
Hi Keijiro, nice tool!

I'm trying to test it but I'm getting the following error after clicking the Generate button:

```
NullReferenceException: Object reference not set to an instance of an object
AIShader.OpenAIUtil.InvokeChat (System.String prompt) (at Assets/Editor/OpenAIUtil.cs:48)
AIShader.AIShaderImporterEditor.Regenerate () (at Assets/Editor/AIShaderImporterEditor.cs:28)
AIShader.AIShaderImporterEditor.OnInspectorGUI () (at Assets/Editor/AIShaderImporterEditor.cs:51)
UnityEditor.UIElements.InspectorElement+<>c__DisplayClass71_0.<CreateIMGUIInspectorFromEditor>b__0 () (at <d18341e808be4529a1a4512a7e51ab3d>:0)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr, Boolean&)
```

I made sure to set the API token. Any thoughts?

Kind regards,

Diego Guisasola

**Comment by keijiro** [comment]
Please check issue #1 .

I close this issue at the moment. Please reopen it if you can't solve your issue based on the information in #1 .

**Comment by diegoguisasolap** [comment]
Hi!
I missed telling you that I did try issue #1. Could you re-open it, please? Thanks a lot!

**Comment by keijiro** [comment]
Then could you try this? https://github.com/keijiro/AIShader/issues/1#issuecomment-1457290094

**Comment by diegoguisasolap** [comment]
Yep, that was the same issue. Sorry for duplicating it!

Invoke-RestMethod : {
    "error": {
        "message": "You exceeded your current quota, please check your plan and billing details.",
        "type": "insufficient_quota",
        "param": null,
        "code": null
    }
}

**Comment by keijiro** [comment]
Then I close this issue.
