### ISSUE TITLE
string

### ISSUE THREAD

**Issue by Raghav-gamedev** [keijiro/AIShader#6]
\OpenAIUtil.cs(28,59): error CS1503: Argument 3: cannot convert from 'string' to 'byte[]'
OpenAIUtil.cs(28,28): error CS1503: Argument 2: cannot convert from 'string' to 'System.Collections.Generic.List<UnityEngine.Networking.IMultipartFormSection>'

**Comment by keijiro** [comment]
Please check the system requirements (Unity version) on README.

**Comment by keijiro** [comment]
I close this issue as answered. Please reopen it if it still reproduces.
