### ISSUE TITLE
Null Reference Exception (Debug Error)

### ISSUE THREAD

**Issue by HilamGhost** [keijiro/AIShader#7]
NullReferenceException: Object reference not set to an instance of an object
AIShader.OpenAIUtil.InvokeChat (System.String prompt) (at Assets/Editor/OpenAIUtil.cs:48)
AIShader.AIShaderImporterEditor.Regenerate () (at Assets/Editor/AIShaderImporterEditor.cs:28)
AIShader.AIShaderImporterEditor.OnInspectorGUI () (at Assets/Editor/AIShaderImporterEditor.cs:51)
UnityEditor.UIElements.InspectorElement+<>c__DisplayClass71_0.<CreateIMGUIInspectorFromEditor>b__0 () (at <d18341e808be4529a1a4512a7e51ab3d>:0)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr, Boolean&)

How can I Fix this?

**Comment by HilamGhost** [comment]
I put my Key In Project Setting btw.

**Comment by keijiro** [comment]
Please check #1 . (Have you registered your valid credit card?)

**Comment by keijiro** [comment]
I close this issue as answered. Please reopen it if it still reproduces.
