### ISSUE TITLE
NullReferenceException Error

### ISSUE THREAD

**Issue by semiromest** [keijiro/AIShader#8]
I wrote prompt and I clicked generate and gave me this error.

NullReferenceException: Object reference not set to an instance of an object
AIShader.OpenAIUtil.InvokeChat (System.String prompt) (at Assets/Scenes/AIShader-main/Assets/Editor/OpenAIUtil.cs:48)
AIShader.AIShaderImporterEditor.Regenerate () (at Assets/Scenes/AIShader-main/Assets/Editor/AIShaderImporterEditor.cs:28)
AIShader.AIShaderImporterEditor.OnInspectorGUI () (at Assets/Scenes/AIShader-main/Assets/Editor/AIShaderImporterEditor.cs:51)
UnityEditor.UIElements.InspectorElement+<>c__DisplayClass71_0.<CreateIMGUIInspectorFromEditor>b__0 () (at <fb48b454ac8e48ea94ca980d999e307f>:0)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr, Boolean&)

this code reference "return data.choices[0].message.content;"

How can I solve this problem?

**Comment by keijiro** [comment]
Please check issue #1
(Check if your credit card is valid)

**Comment by keijiro** [comment]
I close this issue now. Please reopen it if it still reproduces.
