### ISSUE TITLE
NullreferenceExeption

### ISSUE THREAD

**Issue by tremuska** [keijiro/AIShader#9]
I didn't changed anything other than my API key. I used same version. I am %100 sure i have a ChatGPT Plus membership. 

NullReferenceException: Object reference not set to an instance of an object
AIShader.OpenAIUtil.InvokeChat (System.String prompt) (at Assets/Editor/OpenAIUtil.cs:48)
AIShader.AIShaderImporterEditor.Regenerate () (at Assets/Editor/AIShaderImporterEditor.cs:28)
AIShader.AIShaderImporterEditor.OnInspectorGUI () (at Assets/Editor/AIShaderImporterEditor.cs:51)
UnityEditor.UIElements.InspectorElement+<>c__DisplayClass71_0.<CreateIMGUIInspectorFromEditor>b__0 () (at <d18341e808be4529a1a4512a7e51ab3d>:0)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr, Boolean&)

**Comment by keijiro** [comment]
Please check #1 
(your credit card on the OpenAI account is valid?)

**Comment by keijiro** [comment]
I close this issue as answered. Please reopen it if it still reproduces.

**Comment by tremuska** [comment]
As i mentioned earlier. I am %100 sure i have a ChatGPT Plus membership. It is definitely not the credit card issue. I've already check all issues on this repo and i repeat i am pretty sure my credit card is valid and i have plus membership

**Comment by keijiro** [comment]
ChatGPT Plus membership is not relevant. You have to set a valid credit card with your OpenAI developer account.

**Comment by tremuska** [comment]
Oh i see. ChatGPT API and ChatGPT Plus subscription are billed separately. I didn't used api before and I was thinking they already have my credit card info. What's the deal. I think it is very common pit fall. It would be nice if you add this info in the read me section
